news:
    input_length: 600
    channels: 50
    kernel_size: 9
    stride: 1
    learn_rate: 0.0005
    n_epochs: 40
    hidden_layer_nodes: 200
    output_layer_nodes: 5

newsgrp:
    input_length: 600
    channels: 50
    kernel_size: 5
    stride: 1
    learn_rate: 0.001
    n_epochs: 40
    hidden_layer_nodes: 100
    output_layer_nodes: 20
