news:
    kernel_size: 5
    stride: 1
    learn_rate: 0.001
    n_epochs: 40
    hidden_layer_nodes: 100

newsgrp:
    kernel_size: 5
    stride: 1
    learn_rate: 0.001
    n_epochs: 40
    hidden_layer_nodes: 100
